#!/bin/sh -e
# shellcheck disable=1090
# A directory based kiss-hook manager.

hook() {
    [ -e "${KISS_HOOK_DIR:=${KISS_HOOK%/*}}/$TYPE" ] || return 0
    [ -e "$KISS_HOOK_DIR/lib" ] && . "$KISS_HOOK_DIR/lib"

    [ -d "$KISS_HOOK_DIR/$TYPE" ] || {
        . "$KISS_HOOK_DIR/$TYPE"
        return
    }

    [ -f "$KISS_HOOK_DIR/$TYPE/$TYPE" ] && . "$KISS_HOOK_DIR/$TYPE/$TYPE"
    [ -f "$KISS_HOOK_DIR/$TYPE/$PKG"  ] && . "$KISS_HOOK_DIR/$TYPE/$PKG"

    # We are returning with success, since the package manager already exits
    # with in an error caused by the hooks.
    return 0
}

hook
