#!/bin/sh -e
# shellcheck disable=1090
# A directory based kiss-hook manager.

# We don't want the package manager to exit because of an error here.
set +e

hook() {
    [ -e "${KISS_HOOK_DIR:=${KISS_HOOK%/*}}/$TYPE" ] || return 0
    [ -e "$KISS_HOOK_DIR/lib" ] && . "$KISS_HOOK_DIR/lib"

    [ -d "$KISS_HOOK_DIR/$TYPE" ] || {
        . "$KISS_HOOK_DIR/$TYPE"
        return
    }

    [ -f "$KISS_HOOK_DIR/$TYPE/$TYPE" ] && . "$KISS_HOOK_DIR/$TYPE/$TYPE"
    [ -f "$KISS_HOOK_DIR/$TYPE/$PKG"  ] && . "$KISS_HOOK_DIR/$TYPE/$PKG"
}

hook
set -e
